name: CI/CD 

on: 
    # push:
    #     branches: [main]
    workflow_dispatch:
        inputs:
            environment:
                description: This is a CI/CD workflow that works on workflow_dispatch
                default: dev
                required: true
                type: choice
                options:
                    - dev
                    - prod
                    - staging


    # works only with push:
    # path:
    #     - "**.html"
    #     - "**.yml"

jobs:
    code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code 
              run: echo "Checkout the code"
    build:
        needs: code
        runs-on: ubuntu-latest
        steps: 
            - name: Build the code 
              run: echo "Build the code"
    test:
        needs: build
        runs-on: ubuntu-latest
        steps: 
            - name: Test the code 
              run: echo "Test the code"
    deploy:
        if: inputs.environment=='dev'
        needs: test
        runs-on: ubuntu-latest
        steps: 
            - name: Deploy the code 
              run: echo "Deploy the code"
