name: Deploy_to_Server

on: 
    workflow_call:
        secrets:
          HOSTNAME_EC2:
            required: true
          USERNAME_EC2:
            required: true
          PRIVATEKEY_EC2:
            required: true

jobs: 
    deploy_Server:
        runs-on: ubuntu-latest
        steps:
          - name: Validate Secrets Context
            env: 
                HOST_CHECK: ${{ secrets.HOSTNAME_EC2 }}
                USER_CHECK: ${{ secrets.USERNAME_EC2 }}
            run: |
                echo "Checking if secrets are reaching the reusable workflow..."
                echo "HOSTNAME_EC2 Length: ${#HOST_CHECK}"
                echo "USERNAME_EC2 Length: ${#USER_CHECK}"

          - name: SSH to deploy_Server
            uses: appleboy/ssh-action@v1.0.3
            with: 
                host: ${{ secrets.HOSTNAME_EC2 }}
                username: ${{ secrets.USERNAME_EC2 }}
                key: ${{ secrets.PRIVATEKEY_EC2 }}
                script: |
                    echo "Starting Deployment"
                    mkdir Devops