name: DevSecOps

on: 
    workflow_dispatch:

jobs: 
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secrets-scan:
        uses:  ./.github/workflows/secret-scan.yml

    Dependencies_scan:
        uses: ./.github/workflows/dependencies-scan.yml

    Docker-linter:
        uses: ./.github/workflows/Docker-lint.yml
