name: DevSecOps

on: 
    workflow_dispatch:

jobs: 
    # CI (Continuous Integration with Security Scanning)
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secrets-scan:
        uses:  ./.github/workflows/secret-scan.yml

    Dependencies_scan:
        uses: ./.github/workflows/dependencies-scan.yml

    Docker-linter:
        uses: ./.github/workflows/Docker-lint.yml

    # CD - Build Once the security scans are completed
    Build_and_Push:
        needs: [code-quality, secrets-scan, Dependencies_scan, Docker-linter]
        uses: ./.github/workflows/build_push.yml
        secrets: inherit 
