name: Deploy Flask App

on: 
    workflow_dispatch:

env:
    DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to dockerHub
              uses: docker/login-action@v3
              with:
                username: ${{vars.DOCKERHUB_USER}}
                password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Deploy with Docker Compose
              run: docker compose down && docker compose up --build -d --remove-orphans  # Deploy The application using Docker Compose