name: docker-lint 

on: 
    workflow_call:

jobs:
    docker_linter:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: validate dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with: 
                  dockerfile: Dockerfile